apiVersion: v1
kind: Pod
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  containers:
  - name: gitlab
    image: docker.io/gitlab/gitlab-ee:17.8.1-ee.0
    ports:
      - containerPort: 80
        hostPort: 8080
    env:
      - name: GITLAB_OMNIBUS_CONFIG
        value: |
          external_url 'http://192.168.3.102:8080'
          nginx['listen_port'] = 80
    volumeMounts:
      - mountPath: /var/opt/gitlab
        name: gitlab-data
      - mountPath: /etc/gitlab
        name: gitlab-config
      - mountPath: /var/log/gitlab
        name: gitlab-logs
      - mountPath: /var/opt/gitlab/backups/
        name: gitlab-bk
    resources:
      limits:
        memory: "6Gi"

  volumes:
    - name: gitlab-data
      hostPath:
        path: /home/goten/containers/gitlab/data
        type: DirectoryOrCreate
    - name: gitlab-config
      hostPath:
        path: /home/goten/containers/gitlab/config
        type: DirectoryOrCreate
    - name: gitlab-logs
      hostPath:
        path: /home/goten/containers/gitlab/logs
        type: DirectoryOrCreate
    - name: gitlab-bk
      hostPath:
        path: /home/goten/containers/gitlab/backups
        type: DirectoryOrCreate