:toc:

= Ubuntu初期セットアップ手順

== 設定環境

ハードウェア:: Raspberry Pi 4
OS:: Ubuntu 24.04 Desktop

== 設定手順

=== SDカードにOSをインストール

Raspberry Pi imagerからインストール(デフォルトのまま)


=== 初回起動後の設定

. 電源投入前にRaspberry Piにモニターやキーボードなどを接続しておく

. `Welcome` 画面では `English` を選択し、continueをクリック
+ 
コマンドラインなどは英語のまま使いたいので、Englishを選択しています。

. `keyboard layout` 画面では `Japanese` を選択し、continueをクリック
+ 
接続するキーボードレイアウトにあわせて設定してください。


. `Wireless` 画面では、 `I don't want to...` を選択し、continueをクリック
+
ネットワークの設定は後からコマンドラインで行います。


. `Where are you?` 画面では、`Japan Time` を選択し、continueをクリック

. `Who are you?` 画面では、作成するユーザー情報を入力

. セットアップが始まるので、Applying changeが表示されるまで待つ

. 再起動が始まり、ログイン画面が表示されるので、ログインする


=== ネットワークの設定

==== 無線LANでの設定

. 初期ファイルをバックアップファイルにして、設定用ファイルを作成
+
[source, bash]
----
# 初期ファイルをバックアップファイルにする（不要かも）
$ sudo mv /etc/netplan/50-cloud-init.yaml /etc/netplan/50-cloud-init.yaml_bk 

# 設定用ファイルをコピー
# 先頭についている数字が大きいほうがあとに読まれる仕様らしい
$ sudo cp 50-cloud-init.yaml_bk 99-custom.yaml

$ sudo nano 99-custom.yaml
----

. 設定用ファイルを編集する
+
[source, bash]
----
$ sudo nano /etc/netplan/99-custom.yaml
----

+
[source, yaml]
----
network:
  version: 2
  wifis:
    wlan0:
      renderer: NetworkManager
      match: {}
      dhcp4: true
      access-points:
        "[ssid_name]":
          auth:
            password: "[password]"
----


. 設定用ファイルを提供する
+
[source, bash]
----
$ sudo netplan apply
----


=== aptのミラーサイトを変更
ダウンロード速度向上のため、aptコマンドが参照するリポジトリをjaに変更

. 初期ファイルをバックアップを取り、設定用ファイルを編集
+
[source, bash]
----
# バックアップとしてコピーしておく
$ sudo cp /etc/apt/sources.list.d/ubuntu.sources /etc/apt/sources.list.d/ubuntu.sources_bk

# 編集
$ sudo nano /etc/apt/sources.list.d/ubuntu.sources
----

. `URLs` のに`ja`を含めた形に変更する
+
[source, bash]
----
## See the sources.list(5) manual page for further settings.
Types: deb
# portsの前にjp.を追加
URIs: http://jp.ports.ubuntu.com/ubuntu-ports

## Ubuntu security updates. Aside from URIs and Suites,
## this should mirror your choices in the previous section.
Types: deb
# portsの前にjp.を追加
URIs: http://jp.ports.ubuntu.com/ubuntu-ports
----

. 再起動する
+
[source, bash]
----
# 再起動する
$ sudo reboot now
----


=== パッケージのアップデート

. 日時がずれているとアップデートできないので現在の時刻に合わせる
+
[source, bash]
----
$ sudo date --set='yyyy/mm/dd hh:mm:ss'
# NTPサーバー指定してサービス再起動でもOK
----

. パッケージをアップデート
+
[source, bash]
----
$ sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt clean && sudo reboot now 
----


=== sshの設定

. sshに使用するサービスをインストール
+
[source, bash]
----
$ sudo apt install openssh-server
----

. `openssh-server`サービスを起動し、自動起動するように設定
+
[source, bash]
----
# サービス起動
$ sudo systemctl status ssh
# 自動起動設定
$ sudo systemctl enable ssh
----

. 設定ファイルを開いて、編集する
+
用途に合わせて設定してください。

+
[source, bash]
----
$ sudo nano /etc/ssh/sshd_config
----

+
[source, bash]
----
# rootユーザーでのログインを禁止
PermitRootLogin no
# パスワードを使ったログインを禁止
PasswordAuthentication no
----

. サービスを再起動する
+
[source, bash]
----
$ sudo systemctl restart ssh
----



=== 不要なパッケージの削除
用途に合わせて削除してください。

[source, bash]
----
$ sudo apt remove libreoffice* # オープンオフィス
$ sudo apt remove thunderbird* # メーラー

$ sudo apt autoremove -y

$ sudo reboot now
----

== 詳細設定


=== sshを鍵認証に変更

. ローカルPC側で鍵を作成
+
すでに鍵があれば作業は不要です。
+
[source, bash]
----
$ ssh-keygen -t ed25519

# 変更しない場合はEnter
>>> Enter file in which to save the key:

# パスフレーズを作成する場合は入力
>>> Enter passphrase (empty for no passphrase): 
>>> Enter same passphrase again:

# サーバー側に公開鍵をコピー
$ scp id_ed25519.pub [user_name]@[Host IP]:/home/[user_name]/.ssh/
----


. Ubuntu側で公開鍵を登録
+
[source, bash]
----
# 公開鍵を登録
$ cat ~/.ssh/id_ed25519.pub >> ~/.ssh/authorized_keys

# 公開鍵を削除
$ rm ~/.ssh/*.pub

# ファイルの権限を変更
$ chmod 600 ~/.ssh/authorized_keys

# サービス再起動
$ sudo systemctl restart ssh
----

. 接続確認して問題なくssh接続できればOK

=== IPアドレスの固定

==== 無線LAN

. ネットワーク設定ファイルを開く
+
[source, bash]
----
$ sudo nano /etc/netplan/99-custom.yaml 
----

. 下記のように編集
+
[source, yaml]
----
network:
  version: 2
    wifis:
      wlan0:
        dhcp4: false
        addresses: [IP-ADDRESS/24]
        routes:
          - to: default
            via: [default gateway]
        nameservers:
        addresses: [DNS_IP, 8.8.8.8]
        optional: true
        access-points:
          "[ssid_name]":
            auth:
              password: "[password]"
----


=== 自動ログイン設定
Ubuntu起動後、ログイン画面が不要な場合の設定になります。

. 設定用ファイルを開く
+
[source, bash]
----
$ sudo nano /etc/gdm3/custom.conf
----

. 設定用ファイルに下記内容を追加
+
[source, bash]
----
# Enabling automatic login
#  AutomaticLoginEnable = true
#  AutomaticLogin = user1

# Enabling automatic login
AutomaticLoginEnable = true
AutomaticLogin = [username]
----

. 再起動する

+
[source, bash]
----
$ sudo reboot now
----

. 再起動後、自動ログインされれば成功

## 参考
* 不要なパッケージの削除
    ** https://tenteroring.org/sierra/?p=3605