version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    build:
      ./nginx
    ports:
      - "14080:80"
    volumes:
      - .nginx/html:/usr/share/nginx/html
      - .nginx/conf.d:/etc/nginx/conf.d # nginxのconf.dをマウント